
exp_name: "N2S2_CleanRL"
seed: 5031997
torch_deterministic: true
cuda: false
track: true
wandb_project_name: "N8S1"
capture_video: false
policy_name: "ARPPO"
save_models: true
notes: For Clean RL based standard PPO implementation (discounted rewards)


env_json_path: "/JSON/Environment/ServerAssignment/N8S1.json"
total_timesteps: 1000000
learning_rate: 3.0e-4
num_envs: 1
num_steps: 512
anneal_lr: false
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 10
norm_adv: true
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: ~


reward_scale: .001
obs_scale: 500





