---
root_dir: ~
seed: 5031997
device: "cpu"
deterministic_torch: true
save_models: false

agent:
  policy_name: "Backpressure"
  modified: true


env:
    env_json_path: "/JSON/Environment/Env1/Env1b.json"
    time_limit: 100

wandb:
    project: "SB3"

monitor:
    filename: "backpressure"
    info_keywords: ["backlog",]

eval:
  n_eval_episodes: 10
  deterministic: true
