---
config:
root_dir: ~
notes: "Actor: tanh, 2 hidden layers. Critic: tanh, 2 hidden layers, 128 hidden dim. No imitation"
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

buffer:
  size: 1.0e+8
normalizers:
  obs:
    type: Fixed
    norm_factor: 20
    eps: 1.0e-6
  target:
    update_rate: 0.2
    eps: 1.0e-6

agent:
  policy_name: "SafeLTAPPO-JSQDiscreteActor"
  policy: "SafeLTAPPO-JSQDiscreteActor"
  safe_agent: true
  lta_agent: true
  actor:
    type: "JSQDiscreteActor"
    learning_rate: 2.0e-4
    std_learning_rate: 3.0e-03
    kwargs:
      hidden_dim: 64
      activation: "tanh"
      hidden_layers: 2
  safety:
    safe_policy: "JSQ"
    trigger_state: 20
    mod: "prob"
    mod_args:
      omega: 0.5
    args:
      M: "R"
  critic:
    learning_rate: 1.0e-4
    kwargs:
        hidden_dim: 128
        activation: "tanh"
        hidden_layers: 2
  n_epochs: 10
  kwargs:
    critic_first: false
    recompute_adv: true
    update_epochs: 10 # number of updates to perform per batch
    minibatches: 4 # number of minibatches to break the data up into
    shuffle_mb: true
    alpha: 0.0
    nu: 0
    gamma: 0.95
    gae_lambda: 0.99
    clip_coef: 0.1
    kl_coef: 0.0
    ent_coef: 0.0
    kl_target: 0.01
    grad_clip: 10
    value_clip: 1
    vf_coef: 0.5
    imit_coef: 0.0
    pg_coef: 10.0
    int_coef: 0.0


env:
    env_json_path: "/JSON/Environment/ServerAssignment/N4b.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      record_stats: true
      scale_reward: -40.0

wandb:
    project: "JoinTheShortestQueue"
    group: "Debug"


train:
  num_episodes: 5000
  batch_size: 512
  reset: false

eval:
  n_eval_episodes: 10
  deterministic: true





