---
config:
root_dir: ~
notes: "Actor: tanh, 2 hidden layers. Critic: tanh, 2 hidden layers, 128 hidden dim. No imitation"
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

buffer:
  size: 1.0e+8
normalizers:
  obs_scale_factor: 2.0
  obs:
    type: Fixed
    norm_factor: 20
    eps: 1.0e-6
  target:
    update_rate: ~
    eps: 1.0e-6

agent:
  policy_name: "SafeLTAPPO-TanGaussian"
  policy: "SafeLTAPPO-TanGaussian"
  safe_agent: true
  lta_agent: true
  actor:
    type: "TanGaussian"
    learning_rate: 3.0e-03
    std_learning_rate: 3.0e-04
    kwargs:
      hidden_dim: 64
      init_std: 1
      activation: "tanh"
      hidden_layers: 2
  safety:
    safe_policy: "BP"
    trigger_state: 65
    args:
      M: "R"
  critic:
    type: ~
    learning_rate: 3.0e-04
    kwargs:
        hidden_dim: 64
        activation: "tanh"
        hidden_layers: 2
        beta: 0.0
  n_epochs: 10
  kwargs:
    recompute_adv: false
    update_epochs: 10 # number of updates to perform per batch
    minibatches: 4 # number of minibatches to break the data up into
    alpha: 0.1
    nu: 0.0
    gae_lambda: 0.95
    clip_coef: 0.1
    kl_coef: 0.0
    ent_coef: 0.0
    kl_target: 1
    grad_clip: 10
    clip_vloss: false
    vclip_coef: 1.0
    vf_coef: 0.5
    imit_coef: 0.0
    pg_coef: 1.0
    int_coef: 0.001
    pretrain_minibatches: 1
    pretrain_epochs: 1


env:
    env_json_path: "/JSON/Environment/Env2c.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      record_stats: true
      scale_reward: -500

wandb:
    project: "Env2c"
    group: ""


train:
  num_episodes: 1000
  batch_size: 512
  reset: false
  pretrain_steps: 5000

eval:
  n_eval_episodes: 10
  deterministic: true





