---
config:
root_dir: ~
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

buffer:
  size: 1.0e+8
normalizers:
  obs:
    type: Fixed
    norm_factor: 20
    eps: 1.0e-6
  target:
    update_rate: 0.2
    eps: 1.0e-6

agent:
  policy_name: "SafeLTAPPO-TanGaussian"
  policy: "SafeLTAPPO-TanGaussian"
  safe_agent: true
  lta_agent: true
  actor:
    type: "TanGaussian"
    learning_rate: 1.0e-03
    std_learning_rate: 3.0e-04
    kwargs:
      hidden_dim: 64
      init_std: 1
  safety:
    safe_policy: "BP"
    trigger_state: 31
    args:
      M: "R"
  critic:
    hidden_dim: 64
    learning_rate: 3.0e-03
  n_epochs: 10
  kwargs:
    update_epochs: 10 # number of updates to perform per batch
    minibatches: 4 # number of minibatches to break the data up into
    alpha: 0.2
    nu: 0.5
    gae_lambda: 0.95
    clip_coef: 0.2
    kl_coef: 0.0
    ent_coef: 0.0
    kl_target: 1
    grad_clip: 10
    value_clip: 1
    vf_coef: 0.5
    imit_coef: 1.0
    pg_coef: 10.0
    int_coef: 0.0


env:
    env_json_path: "/JSON/Environment/Triangle/Triangle1.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      record_stats: true
      scale_reward: -50.0

wandb:
    project: "ActionDistTesting"
    group: ~


train:
  num_episodes: 5000
  batch_size: 512
  reset: false

eval:
  n_eval_episodes: 10
  deterministic: true





