
exp_name: "N2S2_CleanRL"
seed: 5031997
torch_deterministic: true
cuda: false
track: false
wandb_project_name: "Clean_RL_PPO"
capture_video: false
policy_name: "PPO"
save_models: true


env_json_path: "/JSON/Environment/MultiStepServerAllocation/MSSA_N2S1.json"
total_timesteps: 500000
learning_rate: 2.5e-4
num_envs: 1
num_steps: 128
anneal_lr: true
gamma: 0.99
num_minibatches: 4
update_epochs: 4
norm_adv: true
clip_vloss: true
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: ~

reward_scale: .0001
obs_scale: 0.01



