---
config:
root_dir: ~
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

buffer:
  size: 1.0e+6
normalizers:
  obs:
    eps: 1.0e-6
  target:
    update_rate: 0.1
    eps: 1.0e-6

agent:
  policy_name: "SAC"
  policy: "SAC"
  safe_agent: false
  actor:
    type: "TanGaussian"
    learning_rate: 3.0e-04
    kwargs:
      hidden_dim: 256
      init_std: 2

  critic:
    type: "SAC"
    hidden_dim: 256
    learning_rate: 3.0e-04
  n_epochs: 10
  kwargs:
    update_epochs: 10 # number of updates to perform per batch
    minibatches: 4 # number of minibatches to break the data up into
    gamma: 0.99
    gae_lambda: 0.95
    clip_coef: 0.2
    kl_coef: 0.0
    ent_coef: 0.0
    kl_target: 1
    grad_clip: 0.5
    value_clip: 1
    vf_coef: 0.5


env:
    env_json_path: "/JSON/Environment/Env1/Env1b.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      record_stats: true
    max_steps: 500

wandb:
    project: "Debug"
    group: "PPO-Gaussian"

train:
  learning_starts: 1000
  log_rate: 10

eval:
  n_eval_episodes: 10
  deterministic: true





