---
config:
notes: ~
root_dir: ~
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

buffer:
  size: 1.0e+7
normalizers:
  obs:
    type: Fixed
    norm_factor: 20
    eps: 1.0e-6
  target:
    update_rate: 0.0
    eps: 1.0e-6

agent:
  policy_name: "SafePPO-Discrete"
  policy: "SafePPO-Discrete"
  safe_agent: true
  lta_agent: false
  mod: ~
  safety:
    safe_policy: "JSQ"
    trigger_state: 20
    args:
      M: "R"
  actor:
    type: "JSQDiscreteActor"
    learning_rate: 3.0e-3
    kwargs:
      hidden_dim: 64
      activation: "tanh"
      hidden_layers: 2

  critic:
    learning_rate: 3.0e-3
    kwargs:
      hidden_dim: 128
      activation: "tanh"
      hidden_layers: 2
  n_epochs: 10
  kwargs:
    update_epochs: 10 # number of updates to perform per batch
    minibatches: 4 # number of minibatches to break the data up into
    critic_error_threshold: 5
    gamma: 0.95
    gae_lambda: 0.95
    clip_coef: 0.2
    kl_coef: 0.0
    ent_coef: 0.0
    kl_target: 0.01
    grad_clip: 10
    value_clip: 1
    vf_coef: 0.5
    imit_coef: 1.0
    pg_coef: 1.0
    int_coef: 0.0


env:
    env_json_path: "/JSON/Environment/ServerAllocation/N4.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      record_stats: true
      scale_reward: -20.0


wandb:
    project: "JoinTheShortestQueue"
    group: "Safety-Testing"


train:
  num_episodes: 2000
  batch_size: 512
  reset: true

eval:
  n_eval_episodes: 10

  deterministic: true





