---
config:
root_dir: ~
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

agent:
  policy_name: PPO
  policy: "MlpPolicy"
  kwargs:
      learning_rate: 3.0e-04
      n_steps: 128
      batch_size: 64
      n_epochs: 10
      gamma: 0.99
      gae_lambda: 0.95
      clip_range: 0.2
      clip_range_vf: null
      normalize_advantage: true
      ent_coef: 0.0
      vf_coef: 0.5
      max_grad_norm: 0.5
      use_sde: false
      sde_sample_freq: -1
      target_kl: null
      stats_window_size: 100
      tensorboard_log: "log_dir"
      policy_kwargs: null
      verbose: 0
      seed: null
      device: "auto"
      _init_setup_model: true

env:
    env_json_path: "/JSON/Environment/Env1/Env1a.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      time_limit: 128

wandb:
    project: "SB3"


monitor:
    filename: "PPO"
    info_keywords: ["backlog",]

learn:
  total_timesteps: 500000

eval:
  n_eval_episodes: 10
  deterministic: true





