---
config:
root_dir: ~
seed: 5031997
device: "cpu"
deterministic_torch: true
tasks:
  - "train"
  - "eval"
  - "test"
save_models: true

load:
  zip_path: saved_models/PPO_Env1a_TRAIN_20230621-123803/best_model

buffer:
  size: 1.0e+7
normalizers:
  obs:
    eps: 1.0e-6
  target:
    update_rate: 0.2
    eps: 1.0e-6

agent:
  policy_name: "SafePPO-Gaussian"
  policy: "SafePPO-Gaussian"
  safe_agent: true
  lta_agent: true
  safety:
    safe_policy: "BP"
    trigger_state: 67
    args:
      M: "R"
  actor:
    type: "Gaussian"
    learning_rate: 3.0e-04
    kwargs:
      hidden_dim: 64
      init_std: 2


  critic:
    hidden_dim: 64
    learning_rate: 3.0e-03
  n_epochs: 10
  kwargs:
    update_epochs: 10 # number of updates to perform per batch
    minibatches: 4 # number of minibatches to break the data up into
    alpha: 0.2
    gae_lambda: 0.95
    clip_coef: 0.2
    kl_coef: 0.0
    ent_coef: 0.0
    kl_target: 1
    grad_clip: ~
    value_clip: 1
    vf_coef: 0.5
    imit_coef: 1.0
    pg_coef: 1.0
    int_coef: 10


env:
    env_json_path: "/JSON/Environment/Env1/Env1b.json"
    wrappers:
      normalize_obs: false
      normalize_reward: false
      record_stats: true

wandb:
    project: "ResetTesting"
    group: "Safety-Testing"


train:
  num_episodes: 2000
  batch_size: 128
  reset: false

eval:
  n_eval_episodes: 10
  deterministic: true





