
exp_name: "M4A1_CleanRL"
env_type: "ServerAllocation"
obs_links: true
seed: 5031998
torch_deterministic: true
cuda: true
track: true
test: true
wandb_project_name: "ServerAllocation_M4A1-O"
capture_video: false
policy_name: "IA-AR-PPO"
save_models: true
notes: For Clean RL based standard PPO implementation (discounted rewards)


env_json_path: "/JSON/Environment/ServerAllocation/M4A1.json"
total_timesteps: 3.0e+6
learning_rate: 3.0e-4
num_envs: 1
num_steps: 256
anneal_lr: false
gamma: 1.0
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 10
norm_adv: true
clip_coef: 0.2
clip_vloss: false
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: ~
alpha: 0.2
nu: -0.1
temperature: 0.3
learn_temperature: true
intervention_penalty: 0.00

hidden_size: ~
hidden_depth: ~

critic_hidden_dims: [2, 64]
actor_hidden_dims: [2, 64]

reward_scale: .001
obs_scale: 200

int_thresh: 35

k: 10
drift_threshold: 0.0
on_policy: true

stable_rollout: true
max_stable_rollout: 1000000



apply_mask: true
stable_policy: MWCQ

window_size: 10000

do_eval: false
eval_freq: 100000
eval_steps: 1.0e+5
test_steps: 1.0e+5

learning_steps: 3.0e+6





